master/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from .views import home

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home, name='home'),
    url(r'^control/', include('control_panel.urls', app_name='control_panel', namespace='control_panel')),
    url(r'^newsletters/', include('newsletters.urls', app_name='newsletters', namespace='newsletters')),    
    url(r'^tutorials/', include('tutorials.urls', app_name='tutorials', namespace='tutorials')),
    url(r'^accounts/', include('accounts.urls', app_name='accounts', namespace='accounts')),
]

newsletters/urls.py
from django.conf.urls import url

from .views import newsletter_signup, newsletter_unsubscribe

urlpatterns = [
    url(r'^sign_up/$', newsletter_signup, name='newsletter_signup'),
    url(r'^unsubscribe/$', newsletter_unsubscribe, name='newsletter_unsubscribe'),
]

newsletters/models.py
from django.db import models

# Create your models here.


class NewsletterUser(models.Model):
    email = models.EmailField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email


class Newsletter(models.Model):
    EMAIL_STATUS_CHOICES = (
        ('Draft', 'Draft'),
        ('Published', 'Published')
    )
    subject = models.CharField(max_length=250)
    body = models.TextField()
    email = models.ManyToManyField(NewsletterUser)
    status = models.CharField(max_length=10, choices=EMAIL_STATUS_CHOICES)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject

newsletters/forms.py
from django import forms
from crispy_forms.helper import FormHelper

from .models import NewsletterUser, Newsletter

class NewsletterUserSignUpForm(forms.ModelForm):
    helper = FormHelper()
    helper.form_show_labels = False

    class Meta:
        model = NewsletterUser
        fields = ['email']

        def clean_email(self):
            email = self.cleaned_data.get('email')

            return email

class NewsletterCreationForm(forms.ModelForm):
    helper = FormHelper()
    helper.form_show_labels = False

    class Meta:
        model = Newsletter
        fields = ['subject', 'body', 'email', 'status']

newsletters/views.py
from django.conf import settings
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.core.mail import send_mail, EmailMultiAlternatives
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template.loader import get_template

from .models import NewsletterUser, Newsletter
from .forms import NewsletterUserSignUpForm, NewsletterCreationForm

def newsletter_signup(request):
    form = NewsletterUserSignUpForm(request.POST or None)

    if form.is_valid():
        instance = form.save(commit=False)
        if NewsletterUser.objects.filter(email=instance.email).exists():
            messages.warning(request, 'Your email already exists in our database.', 'alert alert-warning alert-dismmissible')
        else:
            instance.save()
            messages.success(request, 'Your email has been submitted to the database.', 'alert alert-success alert-dismissible')
            subject = 'Thank you for joining our newsletter'
            from_email = settings.EMAIL_HOST_USER
            to_email = [instance.email]
            with open(settings.BASE_DIR + "/templates/newsletters/sign_up_email.txt") as f:
                signup_message = f.read()
            message = EmailMultiAlternatives(subject=subject, body=signup_message, from_email=from_email, to=to_email)
            html_template = get_template('newsletters/sign_up_email.html').render()
            message.attach_alternative(html_template, 'text/html')
            message.send()
            # signup_message = """Welcome to our Newsletter.  If you would liek to unsubscribe visit http://127.0.0.1:8000/newsletter/unsubscribe"""
            # send_mail(subject=subject, from_email=from_email, recipient_list=to_email, message=signup_message, fail_silently=False)

    context = {
        'form': form,
    }
    template = 'newsletters/sign_up.html'
    return render(request, template, context)

def newsletter_unsubscribe(request):
    form = NewsletterUserSignUpForm(request.POST or None)

    if form.is_valid():
        instance = form.save(commit=False)
        if NewsletterUser.objects.filter(email=instance.email).exists():
            NewsletterUser.objects.filter(email=instance.email).delete()
            messages.success(request, 'Your email has been removed.', 'alert alert-success alert-dismissible')
            subject = 'You have been unsubscribed'
            from_email = settings.EMAIL_HOST_USER
            to_email = [instance.email]
            with open(settings.BASE_DIR + "/templates/newsletters/unsubscribe_email.txt") as f:
                signup_message = f.read()
            message = EmailMultiAlternatives(subject=subject, body=signup_message, from_email=from_email, to=to_email)
            html_template = get_template('newsletters/unsubscribe_email.html').render()
            message.attach_alternative(html_template, 'text/html')
            message.send()
            # signup_message = """Sorry to see you go let us know if there is an issue with our service."""
            # send_mail(subject=subject, from_email=from_email, recipient_list=to_email, message=signup_message, fail_silently=False)
        else:
            messages.warning(request, 'Your email is not in our database.', 'alert alert-warning alert-dismmissible')

    context = {
        'form': form,
    }
    template = 'newsletters/unsubscribe.html'
    return render(request, template, context)

def control_newsletter(request):
    form = NewsletterCreationForm(request.POST or None)

    if form.is_valid():
        instance = form.save()
        newsletter = Newsletter.objects.get(id=instance.id)
        if newsletter.status == "Publish":
            subject = newsletter.subject
            body = newsletter.body
            from_email = settings.EMAIL_HOST_USER
            for email in newsletter.email.all():
                send_mail(subject=subject, from_email=from_email, recipient_list=[email], message=body, fail_silently=True)

    context = {
        'form': form,
    }
    template = 'control_panel/control_newsletter.html'
    return render(request, template, context)
    
def control_newsletter_list(request):
    newsletters = Newsletter.objects.all()
    
    paginator = Paginator(newsletters, 1)
    page = request.GET.get('page')
    
    try:
        items = paginator.page(page)
    except PageNotAnInteger:
        items = paginator.page(1)
    except EmptyPage:
        items = paginator.page(paginator.num_pages)

    index = items.number - 1
    max_index = len(paginator.page_range)
    start_index = index - 5 if index >= 5 else 0
    end_index = index + 5 if index <= max_index - 5 else max_index
    page_range = paginator.page_range[start_index:end_index]

    context = {
        'items': items,
        'page_range': page_range,
    }
    template = 'control_panel/control_newsletter_list.html'

    return render(request, template, context)
    
def control_newsletter_detail(request, pk):
    newsletter = get_object_or_404(Newsletter, pk=pk)
    
    context = {
        'newsletter': newsletter,
    }
    template = 'control_panel/control_newsletter_detail.html'

    return render(request, template, context)
        
def control_newsletter_edit(request, pk):
    newsletter = get_object_or_404(Newsletter, pk=pk)
    
    if request.method == 'POST':
        form = NewsletterCreationForm(request.POST, instance=newsletter)
        
        if form.is_valid:
            newsletter = form.save()
            
            if newsletter.status == 'Published':
                subject = newsletter.subject
                body = newsletter.body
                from_email = settings.EMAIL_HOST_USER
                for email in newsletter.email.all():
                    send_mail(subject=subject, from_email=from_email, recipient_list=[email], message=body, fail_silently=True)
            
            return redirect('control_panel:control_newsletter_detail', pk=newsletter.pk)
            
    else:
        form = NewsletterCreationForm(instance=newsletter)
        
    context = {
        'form': form,
    }
    
    template = 'control_panel/control_newsletter.html'
    
    return render(request, template, context)
        
def control_newsletter_delete(request, pk):
    newsletter = get_object_or_404(Newsletter, pk=pk)
    
    if request.method == 'POST':
        form = NewsletterCreationForm(request.POST, instance=newsletter)
        
        if form.is_valid:
            newsletter.delete
            return redirect('control_panel:control_newsletter_list')
    
    else:
        form = NewsletterCreationForm(instance=newsletter)
        
    context = {
        'form': form,
    }
    
    template = 'control_panel/control_newsletter_delete.html'
    
    return render(request, template, context)
    

templates/newsletters/sign_up.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% crispy form form.helper %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-lg-offset-3">
                <h3 class="text-center">Sign Up for Newsletter</h3>
                {% if messages %}
                    {% for message in messages %}
                        <div {% if message.tags %} class="{{ message.tags }}" {% endif %} role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            {{ message }}
                        </div>
                    {% endfor %}
                {% else %}
                <form method="POST">{% csrf_token %}
                    <div class="input-group">
                        {% crispy form %}
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="submit">Subscribe</button>
                        </span>
                    </div>
                </form>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

templates/newsletters/sign_up_email.html
<html>
    <head>

    </head>

    <body>
        <h2>Welcome to our newsletter</h2>
        <p>Thank you for joining</p>
        <p>To unsubscribe visit this link: <a href="{% url "newsletters:newsletter_unsubscribe" %}">Unsubscribe</a></p>
    </body>
</html>

templates/newsletters/unsubscribe.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% crispy form form.helper %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-lg-offset-3">
                <h3 class="text-center">Unsubscribe Newsletter</h3>
                {% if messages %}
                    {% for message in messages %}
                        <div {% if message.tags %} class="{{ message.tags }}" {% endif %} role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            {{ message }}
                        </div>
                    {% endfor %}
                {% else %}
                <form method="POST">{% csrf_token %}
                    <div class="input-group">
                        {% crispy form %}
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="submit">Unsubscribe</button>
                        </span>
                    </div>
                </form>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

templates/newsletters/unsubscribe_email.html
<html>
    <head>

    </head>

    <body>
        <h2>Sorry to see you go</h2>
        <p>Bye Bye</p>
    </body>
</html>